#!/bin/bash
#######################
#Author:Pradnya
#Date:25-10-2023
#
#This script outputs the free RAM space
######################
set -e
set -x
FREE_SPACE=$(free -mt|grep "Total"|awk  '{print$4}')
TH=300
if [[$FREE_SPACE -lt $TH]]
then 
	echo "WARNING ,RAM IS RUNNING LOW"
else
	echo "RAM IS SUFFICIENT -$FREE_SPACE M"
fi
